### ISSUE TITLE
Several GenBank entries raise RuntimeError due to Unicode characters

### ISSUE THREAD

**Issue by xapple** [dlesl/gb-io#5]
So I went ahead and tested this library by parsing all GenBank entries from:

* https://ftp.ncbi.nlm.nih.gov/genbank/

The parser fails and raises an Exception on two entries out of >200000000 because of an "®" character.

Do you think one could fix this?
Thanks!

* https://ftp.ncbi.nlm.nih.gov/genbank/gbenv56.seq.gz
<img width="804" alt="KR000003" src="https://github.com/dlesl/gb-io/assets/649288/026b65d5-2b78-4e71-acb2-8e56e2f2b195">

* https://ftp.ncbi.nlm.nih.gov/genbank/gbbct902.seq.gz
<img width="834" alt="KR002115" src="https://github.com/dlesl/gb-io/assets/649288/86136e8f-6941-4559-86c7-949ca47fbcba">

**Comment by dlesl** [comment]
Genbank files are supposed to only contain ASCII, but `gb-io` also supports unicode, provided that the input is UTF-8. The problem with these files is that they are actually not valid UTF-8, but rather latin-1 encoding. You can convert the file with `iconv -f latin1 -t utf8`, or in Rust as in [this example](https://github.com/dlesl/gb-io/blob/master/examples/parse_genbank/src/main.rs)

**Comment by xapple** [comment]
What about an option to simply substitute with the Unicode Replacement character � and not raise an exception? I understand there is a spec and that NCBI is not following its own spec here, but I also feel that a GB parser should not choke on files being published by GenBank itself.

**Comment by dlesl** [comment]
Yea, in a way the files published by NCBI define the spec, so it does seem weird to choke on their files. However I'm hesitant to work around it since I think it would be a more surprising behaviour to silently accept these files. BioPython made the same decision for their parser (discusion [here](https://github.com/biopython/biopython/issues/1361)).

So I think the cleanest solution here is for the library's users to preprocess the stream, removing/replacing the invalid characters as they desire.
